import { ArrowLeftIcon } from "@heroicons/react/outline";
import Head from "next/head";
import CommentModal from "../../components/CommentModal";
import Sidebar from "../../components/Sidebar";
import Widgets from "../../components/Widgets";
import Post from "../../components/Post";
import { useRouter } from "next/router";
import { AnimatePresence, motion } from "framer-motion";
import { useSession } from "next-auth/react";

export default function Profile({ newsResults, randomUsersResults }) {
    const { data: session } = useSession();
    const router = useRouter();

    return (
        <div>
            <Head>
                <title>Profile Page</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            {session && (<main className="flex min-h-screen mx-auto">
                {/* Sidebar */}
                <Sidebar />

                {/* Feed */}

                <div className='xl:ml-[25%] border-l border-r xl:min-w-[50%] sm:ml-[5%] flex-grow max-w-xl'>
                    <div className="flex items-center space-x-2  py-2 px-3 sticky top-0 z-50 bg-white border-b border-gray-200">
                        <div className="hoverEffect" onClick={() => router.push("/")}>
                            <ArrowLeftIcon className="h-5 " />
                        </div>
                        <h2 className="text-lg sm:text-xl font-bold cursor-pointer">
                            Tweet
                        </h2>
                    </div>


                    <div className="mt-6 w-fit mx-auto">
                        <img
                            src={session?.user.image}
                            alt="user-img"
                            className="w-[250px] rounded-full xl:mr-2"
                        />
                    </div>
                    <div className="flex flex-col justify-center m-[30%]">
                        <div className="mt-8 ">
                            <h1 className="text-black font-bold text-3xl tracking-wide">{session?.user.name}</h1></div>
                        <div className="mt-3 text-black text-2xl font-bold">
                            <span class="text-gray-500 font-semibold mr-5">Username:</span>
                            @{session?.user.username}
                        </div>
                        <div className="mt-3 text-black font-bold text-2xl">
                            <span class="text-gray-500 font-semibold mr-6">E-mail:</span>
                            {session?.user.email}
                        </div>
                    </div>
                </div>

                {/* Widgets */}

                <Widgets
                    newsResults={newsResults.articles}
                    randomUsersResults={randomUsersResults.results}
                />
            </main>
            )}
        </div>
    );
}

// https://saurav.tech/NewsAPI/top-headlines/category/business/us.json

export async function getServerSideProps() {
    const newsResults = await fetch(
        "https://saurav.tech/NewsAPI/top-headlines/category/business/us.json"
    ).then((res) => res.json());

    // Who to follow section

    const randomUsersResults = await fetch(
        "https://randomuser.me/api/?results=30&inc=name,login,picture"
    ).then((res) => res.json());

    return {
        props: {
            newsResults,
            randomUsersResults,
        },
    };
}